import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

/**
 * Capture Studio Shell V1 -- a separate app package, deliberately never
 * built into the core `flow-creative-capture` package. It never imports
 * any runtime value from the core engine (`src/crypto`, `src/store`,
 * `src/device`, `src/evidence`, `src/documents`, `src/simulator`) because
 * those modules ultimately touch `node:crypto`/`node:sqlite`, which do not
 * exist in a browser bundle. This app consumes only:
 *  - TYPE-ONLY imports from `src/domain` (erased at compile time, zero
 *    runtime footprint, so they carry no bundling risk), and
 *  - a static, precomputed fixture JSON generated by `scripts/generateFixture.ts`,
 *    which DOES run the real engine, but only as a one-off Node script.
 */
export default defineConfig({
  root: '.',
  plugins: [react()],
  build: {
    outDir: 'dist',
    sourcemap: true,
  },
});
